// @transaction
export const REQUEST_TRANSACTION = "REQUEST_TRANSACTION";
export const LOAD_TRANSACTION = "LOAD_TRANSACTION";
export const ADD_TRANSACTION = "ADD_TRANSACTION";
export const DELETE_TRANSACTION = "DELETE_TRANSACTION";
export const CLEAR_TRANSACTIONS = "CLEAR_TRANSACTIONS";
export const FAIL_TRANSACTION = "FAIL_TRANSACTION";
export const UPDATE_TRANSACTION = "UPDATE_TRANSACTION";


